# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-state-dapps-world-us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "dapps-world"
    region         = "us-east-1"
  }
}
