# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  provider "aws" {
    region = "us-east-1"
    profile = "dapps-world"
    allowed_account_ids = ["677160962006"]
    # Use assume role instead named profile / Create Role manually
    #assume_role {
    #    role_arn = "arn:aws:iam::677160962006:role/terragrunt"
    #  }
    # Only these AWS Account IDs may be operated on by this template
    default_tags {
      tags = {
        Environment  = "prod"
        Project      = "scde"
        Tribe        = "smartcontracts"
        Organization = "iog"
        Terraform    = "true"
    }
  }
  }
