grafana_cloud:
<<<<<<< HEAD
    api_key: ENC[AES256_GCM,data:SbeUHK0sSe8RhEwjkZ7iXeZQAnVwpHzBcOFeTuGEwuRjZFVwUOi9JgWo1kBGtrW+GpxCjEthbmff9ENaZf4n+ipT3O/r6YMW6OBvJAr4vMnaPYXeaZ74zr/4EbZmzGgfTvEHZTynt8h7ggMIZs3c7mSQdHDzypBbiTssC02cwZE1hRqYs+6qaBLgdPf3t8S1hlPVG3YXpWiUTzvHOt4yyQ==,iv:a0lMBtcpx41Rz37Gshmciedcg+2vNo5pDUt4U9F+ing=,tag:NBZCj9jpClL6G8aoKNyNzg==,type:str]
    prometheus_username: ENC[AES256_GCM,data:yn83tRIyRg==,iv:SdLLmWyBPI+fEMW4rHoMKwUi9kQgEHLG+Sb0IYbtvIM=,tag:RdbgFkOCHxDv+tWscWklpQ==,type:str]
    loki_username: ENC[AES256_GCM,data:olrAyfgZ,iv:QfDslmWVNw2MuYnOa6OJp6QFFgUEA+lwrJOTHzEe8Ko=,tag:OdgsAmNVtitUCGpGmiSeqg==,type:str]
    tempo_username: ENC[AES256_GCM,data:BrQM9NGR,iv:SLG3j03D/vAe09PMhmbPY0+/5BlWWZ4g+b/5gbdNopI=,tag:Kyz+pYTtFoKgZU8cAkkKuw==,type:str]
    grafana_oncall_access_token: ENC[AES256_GCM,data:d8NZFS8Crmv0VdudLUZa/Qyx9ISWQ9jEcpNIQ3CzOZp2d76igN1Vrma9U5HPnRCP6FSpYSGag1utbADeEuhEEA==,iv:RmEnLnkLgsTGp9I8HofpANfjuB3/FfzzsUucivzwnVQ=,tag:5MdiHvxyO9mdC63GHN7zyw==,type:str]
=======
    api_key: ENC[AES256_GCM,data:cPBj+ibLJmt8EgmT603+/sW7ynXMUd3yqit+5Sd9ErZ4nnVAoY+68lMjrtgOZ8qEBtFWQNx5RdxgdPwnSovS8f+vMaIksQ/JH0uLWEo+XkZccWuOvG++aAsQ8DsCSXDUt6/T0AcWl7Fdv1kRhMPDwQYeHxW6Se3hs0RATvWysnfFNZrH7dzstrasrs5+79pDIHUFlzLKrmlGjJE2tyE1Ew==,iv:pWaG63c3q7Qsy+hnXltQ7JqwCPKhnPaVAHZkDxzl1og=,tag:hGSWPx1e8J+y/wXIqF65kQ==,type:str]
    prometheus_username: ENC[AES256_GCM,data:DtRtcRyovw==,iv:BSHU+4KJ+z66a0s46r7kb69U+hLGnJgInO0EaWEAZK0=,tag:wkeS5MzWUUEZPg/ZQcjAAA==,type:str]
    loki_username: ENC[AES256_GCM,data:wTWc4aEe,iv:d35DY2K6cpiM6g7KtjKyTQN0RjP2zUFJ+QLlVYIFqZc=,tag:GMQeU1o/iMDLGqECSj5DJA==,type:str]
    tempo_username: ENC[AES256_GCM,data:TGg3zTou,iv:bmkgpUlGChOAxET5RNr0SgaoAuBr4lrztc9L8K5hskM=,tag:2viZ4X4mkIvVvCszgIttGQ==,type:str]
>>>>>>> 9ba4b35 (PLT-8878 (#65))
dex:
    clientID: ENC[AES256_GCM,data:P8RVzACAIAtkwEtVQ+bY7HQslXBRmQrHc26uUGmfF1vDwrf1ntDRq38KZUW62L8mNtVqXLFteNb+zJgAa7QY6tLGe0ADfc1E,iv:OMH90eBFU7NEAtlAUyw2wdMgfOVz+VEplHo3F2si+AU=,tag:wCN6cw9F5/fZIqVRZoJFmA==,type:str]
    clientSecret: ENC[AES256_GCM,data:xl7qw2Ej+Cl4bYD16yetVn8YV8Iso8WsfgRGOXSWorGMQrc=,iv:20rLL1SARo1CmaO7o39kQjDa+zRh/IgdYAcgkiEcRS8=,tag:sqZuGaldBPM0nVNbF8pHTw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:677160962006:key/fa4d1d08-ad00-4014-97d2-5ff14e00e1b1
          created_at: "2023-12-12T17:39:34Z"
          enc: AQICAHgpALcUCbJ6IXIyoNVBg1oTqujiOETypdzUT4DiWJC8RwFchnaodVaEgiVH0vP0B0kCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwGOzE3as0EGeQ330AgEQgDuIllxdhOfEjW5tnMUw8fh34sn40hLga+0NaF/EnLFr5GTcBpyNdojmEtYdJIxSKnamMNFXORBtqhC5dw==
          aws_profile: "dapps-world"
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
<<<<<<< HEAD
    lastmodified: "2023-12-12T17:39:34Z"
    mac: ENC[AES256_GCM,data:891OVf/BiszzWbk+ei0hkC0CWodSE638vTpzDV56bEysMrXaJ8h5Fav+zKkB9vg69ys3b4rypPAAcDK5Fh1kABTZnjvuGnqSiSavMiuw2mtDXu58NEoP76okZ7LM+OraGvmbNvs09aKnI1viGdzgrJS8VX9E/ddhqbhQtncjbm4=,iv:PI48Pt8Bd/H3WQf0ljsdFLKwz8JEosUsqGjVvPI/ZEg=,tag:CQlnvMiCWojB9EwfAdgLfQ==,type:str]
=======
    lastmodified: "2023-12-06T19:25:11Z"
    mac: ENC[AES256_GCM,data:uqZ+Y9nVHJ8apScLXT7jdvDSRdfv+u/opRP0V+vG3+tOmO8qTF5A/o93ST1TtSIgojPYjdUKdUWWal6S6mKBlT1r8CrBdmkXv38rTV912W8/rWOJGt0O4oGCl7ckw2KTMJNHRJGI8qxhTIwmgyfZj+8alUjgisFd5Vllhkeapgs=,iv:osvr6uWCE/Fs7mq3Z3QT9PXSTJg2Tjev/d7Q3ambXtc=,tag:V2mmDAORai1dZVTRUeE0TQ==,type:str]
>>>>>>> 9ba4b35 (PLT-8878 (#65))
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
