{{- range $index, $network := .Values.networks }}
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cardano-node-{{ $network }}
  namespace: vela-system
spec:
  components:
  - name: cardano-node-{{ $network }}
    type: webservice
    properties:
      {{ if eq $network "mainnet" }}
      cpu: "2"
      {{ else }}
      cpu: "1"
      {{ end}} 
      {{ if eq $network "mainnet" }}
      memory: 16Gi
      {{ else }}
      memory: 8Gi
      {{ end }}
      env:
      - name: NETWORK
        value: {{ $network }}
      exposeType: ClusterIP
      image: inputoutput/cardano-node
      imagePullPolicy: Always
      ports:
      - expose: true
        port: 8090
        protocol: TCP
      volumeMounts:
        emptyDir:
        - name: ipc
          mountPath: /ipc
    traits:
    - type: sidecar
      properties:
        name: socat
        image: alpine/socat
        args:
        - TCP-LISTEN:8090,bind=0.0.0.0,reuseaddr,fork
        - UNIX-CONNECT:/ipc/node.socket
        volumes:
        - name: ipc
          path: /ipc
    - type: storage
      properties:
        pvc:
        - name: node-data-{{ $network }}
          mountPath: /data
          storageClassName: ebs-sc
          resources:
            requests:
              storage: 500Gi
  policies:
  - name: local-vela-system
    properties:
      clusters:
      - local
      namespace: vela-system
    type: topology
  workflow:
    mode:
      steps: DAG
    steps:
    - meta:
        alias: Deploy To local-vela-system
      name: local-vela-system
      properties:
        policies:
        - local-vela-system
      type: deploy
{{- end }}
